basePath: /api
definitions:
  gorm.DeletedAt:
    properties:
      time:
        type: string
      valid:
        description: Valid is true if Time is not NULL
        type: boolean
    type: object
  internal_auth-supertokens.AuthRequest:
    properties:
      formFields:
        items:
          properties:
            id:
              example: email
              type: string
            value:
              example: email@mail.com
              type: string
          type: object
        type: array
    type: object
  internal_auth-supertokens.AuthResponse:
    properties:
      status:
        type: string
      user:
        $ref: '#/definitions/internal_auth-supertokens.User'
    type: object
  internal_auth-supertokens.User:
    properties:
      email:
        type: string
      id:
        type: string
      tenantIds:
        items:
          type: string
        type: array
      timeJoined:
        type: integer
    type: object
  internal_user.User:
    properties:
      accounts:
        items:
          $ref: '#/definitions/model.Account'
        type: array
      address:
        type: string
      created_at:
        type: string
      deleted_at:
        $ref: '#/definitions/gorm.DeletedAt'
      dob:
        type: string
      email:
        type: string
      first_name:
        type: string
      id:
        type: integer
      last_name:
        type: string
      phone_number:
        type: string
      updated_at:
        type: string
      uuid:
        type: string
    type: object
  model.Account:
    properties:
      balance:
        type: number
      closed_at:
        type: string
      currency:
        type: string
      histories:
        items:
          $ref: '#/definitions/model.AccountHistories'
        type: array
      id:
        type: integer
      opened_at:
        type: string
      status:
        $ref: '#/definitions/model.AccountStatus'
      type:
        $ref: '#/definitions/model.AccountType'
      user_id:
        type: string
    type: object
  model.AccountHistories:
    properties:
      account_id:
        type: integer
      amount:
        type: number
      before_amount:
        type: number
      created_at:
        type: string
      final_amount:
        type: number
      id:
        type: integer
      transaction_id:
        type: string
      type:
        $ref: '#/definitions/model.TransactionOperation'
    type: object
  model.AccountStatus:
    enum:
    - active
    - suspended
    - closed
    type: string
    x-enum-varnames:
    - AccountActive
    - AccountSuspended
    - AccountClosed
  model.AccountType:
    enum:
    - savings
    - checking
    type: string
    x-enum-varnames:
    - AccountSavings
    - AccountChecking
  model.TransactionOperation:
    enum:
    - credit
    - debit
    type: string
    x-enum-varnames:
    - OperationCredit
    - OperationDebit
externalDocs:
  description: Supertokens Auth
  url: https://app.swaggerhub.com/apis/supertokens/FDI
host: localhost:9090
info:
  contact: {}
  description: This is a account service - corebank.
  title: Account Service API
  version: "1.0"
paths:
  /accounts:
    get:
      consumes:
      - application/json
      description: get all related accounts of a user
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/model.Account'
            type: array
      security:
      - BearerAuth: []
      summary: get all account of user
      tags:
      - accounts
    post:
      consumes:
      - application/json
      description: create bank account
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/model.Account'
            type: array
      security:
      - BearerAuth: []
      summary: create bank account
      tags:
      - accounts
  /accounts/:id:
    get:
      consumes:
      - application/json
      description: get account by id
      parameters:
      - description: Account ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.Account'
      security:
      - BearerAuth: []
      summary: get account by id
      tags:
      - accounts
  /auth/signin:
    post:
      consumes:
      - application/json
      description: get token from header fields (check docs for more details request
        example)
      parameters:
      - description: auth signin
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/internal_auth-supertokens.AuthRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/internal_auth-supertokens.AuthResponse'
      summary: Sign in to get token
      tags:
      - auth
  /auth/signup:
    post:
      consumes:
      - application/json
      description: register user (check docs for more details request example)
      parameters:
      - description: auth signup
        in: body
        name: user
        required: true
        schema:
          $ref: '#/definitions/internal_auth-supertokens.AuthRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            type: ""
      summary: Sign up user
      tags:
      - auth
  /users/:id:
    get:
      consumes:
      - application/json
      description: create bank account
      parameters:
      - description: User ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/internal_user.User'
            type: array
      security:
      - BearerAuth: []
      summary: create bank account
      tags:
      - users
securityDefinitions:
  BearerAuth:
    description: Type "Bearer" followed by a space and JWT token (Get JWT from header
      signin st-access-token).
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
